airline_analytics:

  target: airline_dev
  outputs:
    tbc_dev:
      type: clickhouse
      schema: airline_dev
      password: ''
    
    tbc_test:
      type: clickhouse
      schema: airline_test
      password: ''

    tbc_production:
      type: clickhouse
      schema: airline_production
      password: ''

    
    
