airline_analytics:

  target: airline_dev
  outputs:
    airline_dev:
      type: clickhouse
      schema: airline_dev
      password: ''
    
    airline_test:
      type: clickhouse
      schema: airline_test
      password: ''

    airline_production:
      type: clickhouse
      schema: airline_production
      password: ''

    
    
